from sqlalchemy.orm import Session
from app.models.core import Student, Counselor
from app.models.assessment import Assessment, DynamicQuestion, AssessmentResponse
from app.services.ai_service import mindbridge_ai
import json

class AssessmentService:
    def __init__(self):
        self.ai = mindbridge_ai

    def generate_assessment(self, db: Session, student_id: int) -> Assessment:
        # Check if active assessment exists
        active = db.query(Assessment).filter(
            Assessment.student_id == student_id,
            Assessment.is_completed == False
        ).first()
        if active:
            return active

        # Prompt Groq to generate 15 MCQs
        system_prompt = """
        Generate exactly 15 multiple-choice questions (scale 1-5) for a student mental health and mood assessment.
        Output MUST be in valid JSON format:
        {
            "questions": [
                {"order": 1, "text": "Question 1 text..."},
                ...
                {"order": 15, "text": "Question 15 text..."}
            ]
        }
        """
        # Use run_grader for strict JSON evaluation
        try:
            data = self.ai.run_grader(
                system_prompt=system_prompt,
                user_content="Generate the assessment questions.",
                temperature=0.8 # slightly higher temperature for question variety
            )
            questions = data.get("questions", [])
            
            if not questions:
                raise ValueError("No questions generated by AI.")
        except Exception as e:
            print(f"Failed to parse Groq questions: {e}")
            # Fallback
            questions = [{"order": i, "text": f"Fallback question {i}"} for i in range(1, 16)]

        # Create assessment in DB
        new_assessment = Assessment(student_id=student_id)
        db.add(new_assessment)
        db.flush() # get ID

        for q in questions[:15]:
            dq = DynamicQuestion(
                assessment_id=new_assessment.id,
                question_text=q.get("text", "Unknown"),
                order=q.get("order", 0)
            )
            db.add(dq)

        db.commit()
        db.refresh(new_assessment)
        return new_assessment

    def evaluate_and_segregate(self, db: Session, assessment_id: int, responses: list[dict]):
        assessment = db.query(Assessment).filter(Assessment.id == assessment_id).first()
        if not assessment:
            return None

        student = db.query(Student).filter(Student.id == assessment.student_id).first()
        
        # Save responses
        for resp in responses:
            ar = AssessmentResponse(
                assessment_id=assessment_id,
                dynamic_question_id=resp["question_id"],
                score=resp["score"]
            )
            db.add(ar)
        
        db.flush()

        # Build prompt for Groq evaluation
        system_prompt = """
        You are evaluating a student's mental health based on 15 questions answered on a 1-5 scale (1=strongly disagree/poor, 5=strongly agree/excellent).
        Based on the scores, assign them to ONE of three categories:
        1: No counseling needed.
        2: Needs some attention (monitor weekly).
        3: Severe attention (needs mental doctor/counselor).
        
        Provide a short text report to be sent to parents and the counselor.
        Output MUST be valid JSON:
        {
            "category": <int>,
            "report": "<string>"
        }
        """
        
        # Format user input
        user_content = "Student Responses:\n"
        for resp in responses:
            user_content += f"- Q_ID {resp['question_id']}: Score {resp['score']}/5\n"

        try:
            # Use strict grader for evaluation (temp=0.0)
            data = self.ai.run_grader(
                system_prompt=system_prompt,
                user_content=user_content,
                temperature=0.0
            )
            
            category = int(data.get("category", 1))
            report = data.get("report", "Assessment completed.")
        except Exception as e:
            print(f"Failed to evaluate: {e}")
            category = 1
            report = "Failed to parse AI evaluation. Defaulting to category 1."

        # Update Assessment
        assessment.assigned_category = category
        assessment.report_text = report
        assessment.is_completed = True

        # Update Student
        student.risk_category = category
        if category == 1:
            student.assessment_frequency = "MONTHLY"
        else:
            student.assessment_frequency = "WEEKLY"
            
        # Assign counselor if category 2 or 3 and none assigned
        if category in [2, 3] and not student.assigned_counselor_id:
            counselor = self._assign_counselor(db)
            if counselor:
                student.assigned_counselor_id = counselor.id

        db.commit()
        db.refresh(assessment)
        return assessment

    def _assign_counselor(self, db: Session) -> Counselor:
        # Simple load balancing: find counselor with fewest students (< 50)
        from sqlalchemy import func
        counselors = db.query(Counselor).all()
        best_counselor = None
        min_students = 51

        for c in counselors:
            count = db.query(Student).filter(Student.assigned_counselor_id == c.id).count()
            if count < min_students and count < 50:
                min_students = count
                best_counselor = c

        return best_counselor

assessment_service = AssessmentService()
